CREATE TABLE GPS_DATA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BUS_NO VARCHAR(255),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    TIMESTAMP DATETIME
);

CREATE INDEX idx_bus_no ON GPS_DATA (BUS_NO);

CREATE INDEX idx_timestamp ON GPS_DATA (TIMESTAMP);
