CREATE TABLE UPDATES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_ID BIGINT,
    UPDATED_TIME VARCHAR(255),
    NEW_STATUS VARCHAR(255),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(id) -- Assumes there is a VEHICLE table with an 'id' column
);
