CREATE TABLE VEHICLE_INFO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_TYPE VARCHAR(255),
    VEHICLE_NO VARCHAR(255),
    VEHICLE_STATUS VARCHAR(255),
    VEHICLE_PLATFROM VARCHAR(255),
    VEHICLE_ARRIVAL_TIME VARCHAR(50),
    VEHICLE_DEPARTURE_TIME VARCHAR(50),
    VEHICLE_LOCATION VARCHAR(255),
    VEHICLE_DEPARTURE_LOCATION VARCHAR(255),
    VEHICLE_ARRIVAL_LOCATION VARCHAR(255),
    VEHICLE_ASSIGNED_ROUTE_ID VARCHAR(255),
    VEHICLE_CURRENT_LOCATION VARCHAR(255),
    VEHICLE_LAST_UPDATE_TIME BIGINT
);

CREATE INDEX idx_vehicle_no ON VEHICLE_INFO (VEHICLE_NO);

CREATE INDEX idx_vehicle_type ON VEHICLE_INFO (VEHICLE_TYPE);

CREATE INDEX idx_vehicle_status ON VEHICLE_INFO (VEHICLE_STATUS);
